### ISSUE TITLE
Question for the depth map?

### ISSUE THREAD

**Issue by SYSUykLin** [OrangeSodahub/SceneCraft#3]
Hello:
  great work!! I want to run on my own dataset. But I don't know the type of the segmentation map and depth map. For example, I have seg map and depth map:
![depth](https://github.com/user-attachments/assets/dd0e932d-89b2-4b07-a09b-576425dd3c23)
![segmentation](https://github.com/user-attachments/assets/6ac54fba-7fb1-41a0-be41-246b770d4f3b)

What kind of transformation should I perform to make the depth map and segmentation map correctly input into your model and run properly? For example, the type of the depth map is gray map, or seg map is one hot or rgb type the same as the hypersim. Thanks

**Comment by OrangeSodahub** [comment]
Hi, thanks for your interest in this work!

First, the depth map used in our model is a [H, W] shaped map with float values (in meters unit). For seg map in one_hot format, it is also a [H, W] shaped map with int values (label indices).

For your issue, it is wierd to have a channel dimention equal to 3. Could you please add a breakpoint here:

https://github.com/OrangeSodahub/SceneCraft/blob/6568a2c9da79beab8c5004db0a9fd26589e89c76/scenecraft/model.py#L845

and check the channels of `image` right after this line? You could tell me the result.

**Comment by SYSUykLin** [comment]
> Hi, thanks for your interest in this work!
> 
> First, the depth map used in our model is a [H, W] shaped map with float values (in meters unit). For seg map in one_hot format, it is also a [H, W] shaped map with int values (label indices).
> 
> For your issue, it is wierd to have a channel dimention equal to 3. Could you please add a breakpoint here:
> 
> https://github.com/OrangeSodahub/SceneCraft/blob/6568a2c9da79beab8c5004db0a9fd26589e89c76/scenecraft/model.py#L845
> 
> and check the channels of `image` right after this line? You could tell me the result.

Thanks very much.

1. Yes, I read the code. And if the condition image is segmentation(labels), it will encode the image and output [2, 8, H, W]. But if the condition image is depth, it do nothing. So after:
https://github.com/OrangeSodahub/SceneCraft/blob/6568a2c9da79beab8c5004db0a9fd26589e89c76/scenecraft/model.py#L845
seg map: [2, 8, H, W]. depth map: [2, 1, H, W]
2. Sorry, I made a mistake. The error is:
```
  File "/cluster/personal/NeRF_projects/NeRF/diffusers/SceneCraft/scenecraft/model.py", line 603, in forward
    raise ValueError(f"Wrong channels of input condition, expected {self.config.conditioning_channels}, "
ValueError: Wrong channels of input condition, expected 8, got 1.
```
And the error code is:
https://github.com/OrangeSodahub/SceneCraft/blob/6568a2c9da79beab8c5004db0a9fd26589e89c76/scenecraft/model.py#L598

I think that I might be missing a depth encoder?

**Comment by OrangeSodahub** [comment]
Nah indice_to_embedding = None is not the issue.

For seg map, the input channels should be 8. and for depth map it should be 1:

https://huggingface.co/gzzyyxy/layout_diffusion_hypersim_prompt_one_hot_multi_control_bs32_epoch24/blob/1d27df15c619672e64377467e8973d5e116cb36d/checkpoint-10900/multicontrolnetmodel_1/config.json#L21

Could you please let me know the error above is popped when the input image is seg map or depth map?

**Comment by SYSUykLin** [comment]
> Nah indice_to_embedding = None is not the issue.
> 
> For seg map, the input channels should be 8. and for depth map it should be 1:
> 
> https://huggingface.co/gzzyyxy/layout_diffusion_hypersim_prompt_one_hot_multi_control_bs32_epoch24/blob/1d27df15c619672e64377467e8973d5e116cb36d/checkpoint-10900/multicontrolnetmodel_1/config.json#L21
> 
> Could you please let me know the error above is popped when the input image is seg map or depth map?

Thanks for your reply.
1. Sorry, it's possible that I didn't post the full error message. I think is depth map. Error message:
```
You have 2 ControlNets and you have passed 1 prompts. The conditionings will be fixed across the prompts.
Traceback (most recent call last):
  File "/cluster/personal/NeRF_projects/NeRF/diffusers/SceneCraft/scripts/inference.py", line 133, in <module>
    generate_output(control_images, controlnet, pipe, generator)
  File "/cluster/personal/NeRF_projects/NeRF/diffusers/SceneCraft/scripts/inference.py", line 50, in generate_output
    guide_images: List[Image.Image] = pipe(prompts,
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/cluster/personal/NeRF_projects/NeRF/diffusers/SceneCraft/scenecraft/model.py", line 1059, in __call__
    down_block_res_samples, mid_block_res_sample = self.controlnet(
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/cluster/personal/NeRF_projects/NeRF/diffusers/SceneCraft/scenecraft/model.py", line 646, in forward
    down_samples2, mid_sample2 = self.nets[1](
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/cluster/personal/NeRF_projects/NeRF/diffusers/SceneCraft/scenecraft/model.py", line 603, in forward
    raise ValueError(f"Wrong channels of input condition, expected {self.config.conditioning_channels}, "
ValueError: Wrong channels of input condition, expected 8, got 1.
```
note that
```
 File "/cluster/personal/NeRF_projects/NeRF/diffusers/SceneCraft/scenecraft/model.py", line 646, in forward
    down_samples2, mid_sample2 = self.nets[1](
```
https://github.com/OrangeSodahub/SceneCraft/blob/6568a2c9da79beab8c5004db0a9fd26589e89c76/scenecraft/model.py#L641

nets[1] is depth map.

**Comment by SYSUykLin** [comment]
And I print the shape of the controlnet_cond before feed into the self.nets:
```
        print(controlnet_cond[0].shape)
        down_samples, mid_sample = self.nets[0](
            sample=sample, timestep=timestep, encoder_hidden_states=encoder_hidden_states,
            controlnet_cond=controlnet_cond[0], conditioning_scale=conditioning_scale[0], **kwargs
        )
        print(controlnet_cond[1].shape)

        if not kwargs.get("no_depth_cond", False):
            # depth controlnet
            kwargs.pop("indice_to_embedding", None)
            down_samples2, mid_sample2 = self.nets[1](
                sample=sample, timestep=timestep, encoder_hidden_states=encoder_hidden_states,
                controlnet_cond=controlnet_cond[1], conditioning_scale=conditioning_scale[1], **kwargs
            )
```
controlnet_cond[0].shape is [2, 8, 768, 1024]
controlnet_cond[1].shape is [2, 1, 768, 1024]

**Comment by OrangeSodahub** [comment]
Hi, then it maybe a model loading issue. Since the channels should be set to 1 when loading the model:

https://huggingface.co/gzzyyxy/layout_diffusion_hypersim_prompt_one_hot_multi_control_bs32_epoch24/blob/1d27df15c619672e64377467e8973d5e116cb36d/checkpoint-10900/multicontrolnetmodel_1/config.json#L21

And I noticed you use:

```python
base_model_path = "ckpts/stable-diffusion-2-1"
checkpoint_path = "controlnet_ckpts/layout_diffusion_hypersim_prompt_one_hot_multi_control_bs32_epoch24"
```

Did you download the checkpoints to local disk? If so, I recommend you directly replace the model name to the repo name in huggingface, for example: `gzzyyxy/layout_diffusion_hypersim_prompt_one_hot_multi_control_bs32_epoch24`. I'm not sure that loading from local dick will read the `config.json` correctly or not but you can try what I suggest first.

Before you try that, you can check the `self.nets[1].config.conditioning_channels`, it should be 1 as set in `config.json`. If it is not, try loading from huggingface.

**Comment by OrangeSodahub** [comment]
I tried loading from local folders and that also perform well. So just make sure that `config.json` file is correct. Please let me know if you still cannot address that.

**Comment by SYSUykLin** [comment]
> I tried loading from local folders and that also perform well. So just make sure that `config.json` file is correct. Please let me know if you still cannot address that.

Thanks for your reply.
1. Yes, the problem is error loading.
2.  In MultiControlNetModel, I modify the code:
        controlnets = [
            ControlNetModel.from_pretrained(os.path.join(model_path_to_load, f"{subfolder}/multicontrolnetmodel"), torch_dtype=torch_dtype),
            ControlNetModel.from_pretrained(os.path.join(model_path_to_load, f"{subfolder}/multicontrolnetmodel_1"), torch_dtype=torch_dtype)
        ]
It work. Maybe the version of the diffusers. Thanks for your help. Thanks very much.

**Comment by SYSUykLin** [comment]
hello:
    last question. Could u provide the corresponding labels and numbers？For example, (bed, 0), (wall, 1), (desk, 2)...  this indices number is the elements of the seg map.
    Thanks.

**Comment by OrangeSodahub** [comment]
I found you proposed data sample is from Hypersim. So you can just follow it (nyu40 labels):

https://github.com/OrangeSodahub/SceneCraft/blob/6568a2c9da79beab8c5004db0a9fd26589e89c76/scenecraft/data/hypersim_utils/meta_data/nyu40id.txt#L1-L3

**Comment by SYSUykLin** [comment]
> I found you proposed data sample is from Hypersim. So you can just follow it (nyu40 labels):
> 
> https://github.com/OrangeSodahub/SceneCraft/blob/6568a2c9da79beab8c5004db0a9fd26589e89c76/scenecraft/data/hypersim_utils/meta_data/nyu40id.txt#L1-L3

Thanks very much.
