### ISSUE TITLE
ValueError: Wrong channels of input condition, expected 8, got 1.

### ISSUE THREAD

**Issue by Minglin-Chen** [OrangeSodahub/SceneCraft#5]
Hi, there! Thanks for your really interesting works! I am trying to train SceneCraft model, but trapped in some errors. Please help me out.

First, I have run the following script to obtain the layout data: 
`bash scripts/generate_outputs.py --layout  --dataset hypersim --scene_id ai_001_001`
Second, I modified L35-L40 in config file `scenecraft/configs/method.py` as follows:
> \# dataset_type="scannetpp",
> \# data=Path("outputs/scannetpp"),
> \# scene_id="0a7cc12c0e",
> dataset_type="hypersim",
> data=Path("outputs/hypersim"),
> scene_id="ai_001_001",

Third, I run the script:
`ns-train nerfacto-big2 --machine.num-devices 2`

Sadly, I got the error:
```
File "/XXX/SceneCraft/scenecraft/model.py", line 598, in forward
    raise ValueError(f"Wrong channels of input condition, expected {self.config.conditioning_channels}, "
ValueError: Wrong channels of input condition, expected 8, got 1.
```

Can you provide a simple solution?

**Comment by OrangeSodahub** [comment]
Hi, don't be sad. Please refer to this issue #3 and this is the solution https://github.com/OrangeSodahub/SceneCraft/issues/3#issuecomment-2444752059

This is a problem caused by the version of diffusers. I will fix it later.

**Comment by Minglin-Chen** [comment]
Thanks, it works!
