### ISSUE TITLE
Some terrible results

### ISSUE THREAD

**Issue by SYSUykLin** [OrangeSodahub/SceneCraft#7]
Hello:
     I've found that the model performs well on a single object, but the results of the generative diffusion model are very poor when there are multiple objects.

seg map:
![image](https://github.com/user-attachments/assets/13c46f36-dad9-430d-95f2-ffac8b72bd3e)
dept map:
![image](https://github.com/user-attachments/assets/f7286220-e9fd-4e24-b801-5ddb17c253af)
results:
![image](https://github.com/user-attachments/assets/76c33c11-2b18-47d2-a75d-851ae5df7e50)
two abnormal results:
1) The purple one is the bookcase, and it cannot be generated correctly
2) Desk and chair are burrly.

How could I fix it? Thanks

**Comment by OrangeSodahub** [comment]
Please strictly follow our code and pipeline. 1) Dont use customed layout whose distribution is too different from dataset itself e.g. size, ratio, etc; 2) your map contains white area and invalid depth values; 3) please try different text instructions which are crucial to the performance.

**Comment by SYSUykLin** [comment]
thanks for your reply.
